name: Build Animus VPN
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Force HTTPS and Deep Sync
        run: |
          # 1. Глобально меняем правила: любой запрос SSH превращаем в HTTPS
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
          
          # 2. Глубокая прошивка всех вложенных модулей
          git submodule init
          git submodule sync --recursive
          git submodule update --init --recursive --depth 1

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: animus-vpn-debug-file
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: animus-vpn-debug-file
          path: build/app/outputs/flutter-apk/app-debug.apk
