name: Build Animus VPN
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: The REAL Submodule Fix
        run: |
          # 1. СНАЧАЛА меняем ссылки в главном корневом файле
          sed -i 's|git@github.com:|https://github.com/|g' .gitmodules
          sed -i 's|ssh://git@github.com/|https://github.com/|g' .gitmodules
          git submodule sync
          
          # 2. ТОЛЬКО ПОТОМ скачиваем первый уровень (hiddify-core)
          git submodule update --init
          
          # 3. Теперь папка появилась. Ищем все новые .gitmodules внутри неё и меняем ссылки
          find . -name ".gitmodules" -type f -exec sed -i 's|git@github.com:|https://github.com/|g' {} +
          find . -name ".gitmodules" -type f -exec sed -i 's|ssh://git@github.com/|https://github.com/|g' {} +
          git submodule sync --recursive
          
          # 4. Безопасно докачиваем самые глубокие слои (ray2sing и т.д.)
          git submodule update --init --recursive

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: animus-vpn-debug-file
          path: build/app/outputs/flutter-apk/app-debug.apk
